blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Git ì „ëµ ë¬¸ì„œ
    url: https://www.notion.so/Git-28077e47f090804092c6fd198e5a9fac
    about: ë¸Œëœì¹˜ ì „ëµ ë° ì‘ì—… í”„ë¡œì„¸ìŠ¤ ë¬¸ì„œë¥¼ í™•ì¸í•˜ì„¸ìš”.
